"""use int

Revision ID: 48dc6fd2b54e
Revises: a4751fd79514
Create Date: 2024-08-03 13:37:44.533238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48dc6fd2b54e'
down_revision: Union[str, None] = 'a4751fd79514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tag_groups', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('tag_groups', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
