"""use int

Revision ID: 13ab1f9ff043
Revises: 48dc6fd2b54e
Create Date: 2024-08-03 22:00:37.540564

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13ab1f9ff043"
down_revision: Union[str, None] = "48dc6fd2b54e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE posts SET score = 0 WHERE score IS NULL")
    op.execute("UPDATE posts SET rating = 0 WHERE rating IS NULL")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column("score", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("rating", existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_index(batch_op.f("ix_posts_file_path"), ["file_path"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_posts_file_path"))
        batch_op.alter_column("rating", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("score", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
