"""empty message

Revision ID: 8212d6a8c4a4
Revises: 713e4bcaf625
Create Date: 2024-11-16 23:41:36.205329

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8212d6a8c4a4"
down_revision: Union[str, None] = "713e4bcaf625"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "full_path",
                sa.String(),
                sa.Computed(
                    "file_path || '/' || file_name || '.' || extension",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "aspect_ratio",
                sa.Float(),
                sa.Computed("width * 1.0 / NULLIF(height, 0)"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_column("aspect_ratio")
        batch_op.drop_column("full_path")
    # ### end Alembic commands ###
