"""empty message

Revision ID: 526c5fd2ff9e
Revises: a64a57040c74
Create Date: 2024-11-16 16:16:44.182988

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "526c5fd2ff9e"
down_revision: Union[str, None] = "a64a57040c74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "full_path",
                sa.String(),
                sa.Computed(
                    "file_path || '/' || file_name || '.' || extension",
                ),
                nullable=True,
            )
        )
        batch_op.create_index(batch_op.f("ix_posts_meta"), ["meta"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_posts_meta"))
        batch_op.drop_column("full_path")

    # ### end Alembic commands ###
