"""empty message

Revision ID: 713e4bcaf625
Revises: 526c5fd2ff9e
Create Date: 2024-11-16 22:07:37.238216

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "713e4bcaf625"
down_revision: Union[str, None] = "526c5fd2ff9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("folders")

    # posts, 将所有字段都设置为非空
    op.execute("UPDATE posts SET caption = '' WHERE caption IS NULL")
    op.execute("UPDATE posts SET description = '' WHERE description IS NULL")
    op.execute("UPDATE posts SET meta = '' WHERE meta IS NULL")
    op.execute("UPDATE posts SET md5 = '' WHERE md5 IS NULL")
    op.execute("UPDATE posts SET source = '' WHERE source IS NULL")
    op.execute("UPDATE posts SET size = 0 WHERE size IS NULL")
    op.execute("UPDATE posts SET width = 0 WHERE width IS NULL")
    op.execute("UPDATE posts SET height = 0 WHERE height IS NULL")
    #     op.execute("UPDATE posts SET aspect_ratio = width * 1.0 / NULLIF(height, 0)")

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_column("full_path")
        batch_op.drop_column("aspect_ratio")
        batch_op.alter_column("width", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("height", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("meta", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("md5", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("size", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("source", existing_type=sa.VARCHAR(), nullable=False)
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "full_path",
                sa.String(),
                sa.Computed(
                    "file_path || '/' || file_name || '.' || extension",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "aspect_ratio",
                sa.Float(),
                sa.Computed("width * 1.0 / NULLIF(height, 0)"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column("source", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("size", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("md5", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("meta", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("height", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("width", existing_type=sa.INTEGER(), nullable=True)

    op.create_table(
        "folders",
        sa.Column("path", sa.VARCHAR(), nullable=False),
        sa.Column("file_count", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("path"),
    )
    # ### end Alembic commands ###
