"""add tag group parent id field

Revision ID: 1b2fa04c6a7b
Revises: 39178cc17d3f
Create Date: 2024-12-10 20:07:50.393522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2fa04c6a7b'
down_revision: Union[str, None] = '39178cc17d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    with op.batch_alter_table('tag_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_tag_groups_parent_id", "tag_groups", ["parent_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_groups', schema=None) as batch_op:
        batch_op.drop_constraint("fk_tag_groups_parent_id", type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
