"""empty message

Revision ID: a64a57040c74
Revises: 209b7e52d3da
Create Date: 2024-11-12 21:35:35.697392

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a64a57040c74"
down_revision: Union[str, None] = "209b7e52d3da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # 删掉前缀包含 _alembic_tmp 的表
    op.execute("UPDATE posts SET caption = '' WHERE caption IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_column("aspect_ratio")
        batch_op.alter_column("caption", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_index("ix_posts_aspect_ratio")
        batch_op.add_column(sa.Column("aspect_ratio", sa.Float, sa.Computed("width * 1.0 / NULLIF(height, 0)")))

    with op.batch_alter_table("tag_groups", schema=None) as batch_op:
        batch_op.alter_column("color", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag_groups", schema=None) as batch_op:
        batch_op.alter_column("color", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index("ix_posts_aspect_ratio", ["aspect_ratio"], unique=False)
        batch_op.alter_column("caption", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("aspect_ratio")
        batch_op.add_column(sa.Column("aspect_ratio", sa.FLOAT(), server_default=sa.text("0.0")))

    op.execute("ALTER TABLE posts ADD COLUMN aspect_ratio FLOAT DEFAULT 0.0")
    # ### end Alembic commands ###
