"""cascade delete

Revision ID: 982ba76522d1
Revises: 8a745d46e446
Create Date: 2025-01-06 13:23:53.399352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982ba76522d1'
down_revision: Union[str, None] = '8a745d46e446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_has_color', schema=None) as batch_op:
        batch_op.drop_constraint('post_has_color_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_has_tag', schema=None) as batch_op:
        batch_op.drop_constraint('post_has_tag_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('post_has_tag_tag_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tags', ['tag_name'], ['name'], ondelete='CASCADE')

    with op.batch_alter_table('tag_groups', schema=None) as batch_op:
        batch_op.drop_constraint('tag_groups_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tag_groups', ['parent_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('tags_group_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tag_groups', ['group_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tags_group_id_fkey', 'tag_groups', ['group_id'], ['id'])

    with op.batch_alter_table('tag_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tag_groups_parent_id_fkey', 'tag_groups', ['parent_id'], ['id'])

    with op.batch_alter_table('post_has_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_has_tag_tag_name_fkey', 'tags', ['tag_name'], ['name'])
        batch_op.create_foreign_key('post_has_tag_post_id_fkey', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('post_has_color', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_has_color_post_id_fkey', 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
